const shopActionTypes={
    START_FETCH_COLLECTIONS:'START_FETCH_COLLECTIONS',
    FETCH_COLLECTIONS_SUCCESS:'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE:'FETCH_COLLECTIONS_FAILURE'
}

export default shopActionTypes;