const CartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    DECREASE_QUANTITY:'DECREASE_QUANTITY',
    CLEAR_CART:'CLEAR_CART',
    UPDATE_CART_IN_FIREBASE:'UPDATE_CART_IN_FIREBASE',
    SET_CART_FROM_FIREBASE:'SET_CART_FROM_FIREBASE'
};

export default CartActionTypes;